-- Enable PostGIS if needed for advanced geo (optional, sticking to float logic for MVP)

-- 1. ZONES Table
CREATE TABLE IF NOT EXISTS zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    min_lat FLOAT8,
    max_lat FLOAT8,
    min_lon FLOAT8,
    max_lon FLOAT8,
    current_status TEXT DEFAULT 'NORMAL', -- NORMAL, WATCH, ALERT
    last_updated TIMESTAMPTZ DEFAULT NOW()
);

-- 2. WEATHER LOGS Table
CREATE TABLE IF NOT EXISTS weather_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id BIGINT REFERENCES zones(id),
    temp FLOAT8,
    humidity FLOAT8,
    recorded_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. FIRE EVENTS Table
CREATE TABLE IF NOT EXISTS fire_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id BIGINT REFERENCES zones(id),
    confidence TEXT,
    lat FLOAT8,
    lon FLOAT8,
    detected_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ALERT HISTORY Table
CREATE TABLE IF NOT EXISTS alert_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id BIGINT REFERENCES zones(id),
    risk_level TEXT,
    message_en TEXT,
    message_sw TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- SEED DATA: Kakamega Forest
-- Lat (0.25 to 0.35), Lon (34.75 to 34.95)
INSERT INTO zones (name, min_lat, max_lat, min_lon, max_lon)
VALUES ('Kakamega Forest', 0.25, 0.35, 34.75, 34.95)
ON CONFLICT DO NOTHING; -- (Note: ID conflict handling depends on implementation, raw SQL injection assumes empty DB or manual check)

-- SEED DATA: Mau Forest (Adding as backup/secondary)
-- Lat (-0.8 to -0.3), Lon (35.3 to 35.8)
INSERT INTO zones (name, min_lat, max_lat, min_lon, max_lon)
VALUES ('Mau Forest', -0.8, -0.3, 35.3, 35.8)
ON CONFLICT DO NOTHING;
